const testData = [
    { id: 1, text: 'Product no. 1' },
    { id: 2, text: 'Product no. 2' },
    { id: 3, text: 'Product no. 3' },
    { id: 4, text: 'Product no. 4' },
    { id: 5, text: 'Product no. 5' },
    { id: 6, text: 'Product no. 6' },
    { id: 7, text: 'Product no. 7' },
    { id: 8, text: 'Product no. 8' },
    { id: 9, text: 'Product no. 9' },
    { id: 10, text: 'Product no. 10' },
    { id: 11, text: 'Product no. 11' },
    { id: 12, text: 'Product no. 12' },
    { id: 13, text: 'Product no. 13' },
    { id: 14, text: 'Product no. 14' },
    { id: 15, text: 'Product no. 15' },
    { id: 16, text: 'Product no. 16' },
    { id: 17, text: 'Product no. 17' },
    { id: 18, text: 'Product no. 18' },
    { id: 19, text: 'Product no. 19' },
    { id: 20, text: 'Product no. 20' },
    { id: 21, text: 'Product no. 21' },
    { id: 22, text: 'Product no. 22' },
    { id: 23, text: 'Product no. 23' },
    { id: 24, text: 'Product no. 24' },
    { id: 25, text: 'Product no. 25' },
    { id: 26, text: 'Product no. 26' },
    { id: 27, text: 'Product no. 27' },
    { id: 28, text: 'Product no. 28' },
    { id: 29, text: 'Product no. 29' },
    { id: 30, text: 'Product no. 30' },
    { id: 31, text: 'Product no. 31' },
    { id: 32, text: 'Product no. 32' },
    { id: 33, text: 'Product no. 33' },
    { id: 34, text: 'Product no. 34' },
    { id: 35, text: 'Product no. 35' },
    { id: 36, text: 'Product no. 36' },
    { id: 37, text: 'Product no. 37' },
    { id: 38, text: 'Product no. 38' },
    { id: 39, text: 'Product no. 39' },
    { id: 40, text: 'Product no. 40' },
    { id: 41, text: 'Product no. 41' },
    { id: 42, text: 'Product no. 42' },
    { id: 43, text: 'Product no. 43' },
    { id: 44, text: 'Product no. 44' },
    { id: 45, text: 'Product no. 45' },
    { id: 46, text: 'Product no. 46' },
    { id: 47, text: 'Product no. 47' },
    { id: 48, text: 'Product no. 48' },
    { id: 49, text: 'Product no. 49' },
    { id: 50, text: 'Product no. 50' }
];



export default testData;